# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBr5ieryL-nipVYDsb0vcsSUgby4SIDZ
"""

import streamlit as st
from transformers import T5Tokenizer, T5ForConditionalGeneration

# Load model from local folder
model = T5ForConditionalGeneration.from_pretrained("t5-model")
tokenizer = T5Tokenizer.from_pretrained("t5-model")

# Inference
def generate_code(query):
    input_text = "generate code: " + query.lower()
    input_ids = tokenizer.encode(input_text, return_tensors="pt", max_length=128, truncation=True, padding="max_length")
    outputs = model.generate(input_ids, max_length=128, num_beams=4, early_stopping=True)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# UI
st.title("Code Generator (T5)")
query = st.text_input("Enter your coding query:")
if st.button("Generate Code"):
    if query:
        st.code(generate_code(query), language="python")
    else:
        st.warning("Please enter a prompt!")

